name = "Kanagawa Dragon"
version = "0.1.0"

authors = [
    "Ahum Maitra (@TheAhumMaitra) theahummaitra@gmail.com",
]

license = "GPL-3.0-or-later"

[gtk]
theme_name = "Yaru-blue-dark"
icon_theme = "Yaru-blue"

[vscode]
publisher = "metaphore"
extension_name = "kanagawa-vscode-color-theme"
theme_name = "Kanagawa Dragon"
